{"name": "Log in with existing account - security invalid", "status": "passed", "description": "Invalid security error will pop up", "steps": [{"name": "Logging into account with invalid security code", "status": "passed", "start": 1680022349209, "stop": 1680022352234}, {"name": "Asserting error message", "status": "passed", "start": 1680022352234, "stop": 1680022352249}], "start": 1680022349209, "stop": 1680022352249, "uuid": "c3512aa1-a3fe-45f0-8a68-b979aec125f4", "historyId": "392494e07be8f9c69981383fc1e62af1", "testCaseId": "a9ed3ccebe1d067029d52bf5e9e06de7", "fullName": "Test_Login#test_log_in_invalid_security", "labels": [{"name": "severity", "value": "critical"}, {"name": "epic", "value": "Test Login"}, {"name": "as_id", "value": 13}, {"name": "suite", "value": "Test_Login"}, {"name": "host", "value": "TWEEJ5"}, {"name": "thread", "value": "18924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Login"}]}